import { and, eq } from "drizzle-orm";
import type { NodePgDatabase } from "drizzle-orm/node-postgres";
import { builds, stageOutputs } from "./schema";

// Stage outputs are Postgres uuids; a non-uuid string makes the uuid column
// comparison throw, so guard lookups and treat malformed ids as "not found".
const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export const EDITED_CONTENT_MAX_LENGTH = 20_000;

export type EditedContentValidation =
  | { ok: true; value: string }
  | { ok: false; error: string };

/**
 * Validate a founder's inline edit before it overwrites `editedOutput`.
 * Trims surrounding whitespace and rejects empty or oversized submissions.
 */
export function validateEditedContent(raw: unknown): EditedContentValidation {
  if (typeof raw !== "string") {
    return { ok: false, error: "Add some content before saving your edit." };
  }

  const value = raw.trim();

  if (value.length === 0) {
    return { ok: false, error: "Add some content before saving your edit." };
  }

  if (value.length > EDITED_CONTENT_MAX_LENGTH) {
    return {
      ok: false,
      error: `Keep your edit under ${EDITED_CONTENT_MAX_LENGTH} characters.`,
    };
  }

  return { ok: true, value };
}

/** Founder-facing text for a jsonb output: strings as-is, objects pretty-printed. */
export function stageOutputText(value: unknown): string {
  if (value === null || value === undefined) {
    return "";
  }
  if (typeof value === "string") {
    return value;
  }
  return JSON.stringify(value, null, 2);
}

/** Founder-facing view of a Stage output: raw/edited jsonb resolved to display text. */
export interface StageOutputDisplay {
  id: string;
  buildId: string;
  stageIndex: number;
  stageName: string;
  rawText: string;
  editedText: string | null;
}

/** Shared by the API route response and the session page's server-side fetch. */
export function toStageOutputView(record: StageOutputRecord): StageOutputDisplay {
  return {
    id: record.id,
    buildId: record.buildId,
    stageIndex: record.stageIndex,
    stageName: record.stageName,
    rawText: stageOutputText(record.rawOutput),
    editedText: record.editedOutput === null ? null : stageOutputText(record.editedOutput),
  };
}

/** A persisted Stage output as returned to callers. */
export interface StageOutputRecord {
  id: string;
  buildId: string;
  stageIndex: number;
  stageName: string;
  rawOutput: unknown;
  editedOutput: unknown | null;
  approvedAt: Date | null;
}

export interface CreateStageOutputInput {
  buildId: string;
  stageIndex: number;
  stageName: string;
  rawOutput: unknown;
}

/**
 * Persistence boundary for Stage outputs. Implemented by
 * {@link DrizzleStageOutputsRepository} for real Postgres and
 * {@link InMemoryStageOutputsRepository} for tests and local runs without a
 * database configured.
 *
 * MVP assumption: one row per (build, stageIndex) — a stage is regenerated by
 * overwriting, not versioned.
 */
export interface StageOutputsRepository {
  /** Insert a generated output. `ownerUserId` must own the build, else returns null. */
  create(
    input: CreateStageOutputInput,
    ownerUserId: string,
  ): Promise<StageOutputRecord | null>;
  /** Ownership-gated read: null when missing OR when the build isn't the user's. */
  getForUser(
    buildId: string,
    stageIndex: number,
    userId: string,
  ): Promise<StageOutputRecord | null>;
  listForUser(buildId: string, userId: string): Promise<StageOutputRecord[]>;
  /** Overwrite editedOutput only (rawOutput untouched). Null when missing/not owned. */
  saveEditForUser(
    buildId: string,
    stageIndex: number,
    userId: string,
    editedOutput: unknown,
  ): Promise<StageOutputRecord | null>;
}

type StageOutputRow = typeof stageOutputs.$inferSelect;

function toRecord(row: StageOutputRow): StageOutputRecord {
  return {
    id: row.id,
    buildId: row.buildId ?? "",
    stageIndex: row.stageIndex,
    stageName: row.stageName,
    rawOutput: row.rawOutput ?? null,
    editedOutput: row.editedOutput ?? null,
    approvedAt: row.approvedAt ?? null,
  };
}

/** Drizzle/Postgres-backed repository used at runtime when DATABASE_URL is set. */
export class DrizzleStageOutputsRepository implements StageOutputsRepository {
  constructor(private readonly db: NodePgDatabase) {}

  private async isOwnedByUser(buildId: string, userId: string): Promise<boolean> {
    if (!UUID_PATTERN.test(buildId)) {
      return false;
    }
    const [row] = await this.db
      .select()
      .from(builds)
      .where(and(eq(builds.id, buildId), eq(builds.userId, userId)))
      .limit(1);
    return Boolean(row);
  }

  async create(
    input: CreateStageOutputInput,
    ownerUserId: string,
  ): Promise<StageOutputRecord | null> {
    if (!(await this.isOwnedByUser(input.buildId, ownerUserId))) {
      return null;
    }
    const [row] = await this.db
      .insert(stageOutputs)
      .values({
        buildId: input.buildId,
        stageIndex: input.stageIndex,
        stageName: input.stageName,
        rawOutput: input.rawOutput,
      })
      .returning();
    return toRecord(row);
  }

  async getForUser(
    buildId: string,
    stageIndex: number,
    userId: string,
  ): Promise<StageOutputRecord | null> {
    if (!(await this.isOwnedByUser(buildId, userId))) {
      return null;
    }
    const [row] = await this.db
      .select()
      .from(stageOutputs)
      .where(
        and(eq(stageOutputs.buildId, buildId), eq(stageOutputs.stageIndex, stageIndex)),
      )
      .limit(1);
    return row ? toRecord(row) : null;
  }

  async listForUser(buildId: string, userId: string): Promise<StageOutputRecord[]> {
    if (!(await this.isOwnedByUser(buildId, userId))) {
      return [];
    }
    const rows = await this.db
      .select()
      .from(stageOutputs)
      .where(eq(stageOutputs.buildId, buildId))
      .orderBy(stageOutputs.stageIndex);
    return rows.map(toRecord);
  }

  async saveEditForUser(
    buildId: string,
    stageIndex: number,
    userId: string,
    editedOutput: unknown,
  ): Promise<StageOutputRecord | null> {
    if (!(await this.isOwnedByUser(buildId, userId))) {
      return null;
    }
    const [row] = await this.db
      .update(stageOutputs)
      .set({ editedOutput })
      .where(
        and(eq(stageOutputs.buildId, buildId), eq(stageOutputs.stageIndex, stageIndex)),
      )
      .returning();
    return row ? toRecord(row) : null;
  }
}

interface InMemoryStageOutputRow extends StageOutputRecord {
  ownerUserId: string;
}

/**
 * In-memory repository. Backs tests and local/e2e runs without a database.
 * Ownership is tracked via a memory-only `ownerUserId` field (not part of the
 * DB schema) so ownership gating can be exercised without Postgres.
 */
export class InMemoryStageOutputsRepository implements StageOutputsRepository {
  private readonly rows = new Map<string, InMemoryStageOutputRow>();

  private key(buildId: string, stageIndex: number): string {
    return `${buildId}:${stageIndex}`;
  }

  private copy(row: InMemoryStageOutputRow): StageOutputRecord {
    return {
      id: row.id,
      buildId: row.buildId,
      stageIndex: row.stageIndex,
      stageName: row.stageName,
      rawOutput: row.rawOutput,
      editedOutput: row.editedOutput,
      approvedAt: row.approvedAt,
    };
  }

  async create(
    input: CreateStageOutputInput,
    ownerUserId: string,
  ): Promise<StageOutputRecord | null> {
    const row: InMemoryStageOutputRow = {
      id: crypto.randomUUID(),
      buildId: input.buildId,
      stageIndex: input.stageIndex,
      stageName: input.stageName,
      rawOutput: input.rawOutput,
      editedOutput: null,
      approvedAt: null,
      ownerUserId,
    };
    this.rows.set(this.key(input.buildId, input.stageIndex), row);
    return this.copy(row);
  }

  async getForUser(
    buildId: string,
    stageIndex: number,
    userId: string,
  ): Promise<StageOutputRecord | null> {
    const row = this.rows.get(this.key(buildId, stageIndex));
    if (!row || row.ownerUserId !== userId) {
      return null;
    }
    return this.copy(row);
  }

  async listForUser(buildId: string, userId: string): Promise<StageOutputRecord[]> {
    return Array.from(this.rows.values())
      .filter((row) => row.buildId === buildId && row.ownerUserId === userId)
      .sort((a, b) => a.stageIndex - b.stageIndex)
      .map((row) => this.copy(row));
  }

  async saveEditForUser(
    buildId: string,
    stageIndex: number,
    userId: string,
    editedOutput: unknown,
  ): Promise<StageOutputRecord | null> {
    const row = this.rows.get(this.key(buildId, stageIndex));
    if (!row || row.ownerUserId !== userId) {
      return null;
    }
    row.editedOutput = editedOutput;
    return this.copy(row);
  }
}
