// @vitest-environment jsdom
import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { StageOneResult } from "./StageOneResult";

describe("StageOneResult", () => {
  it("renders the idea summary fields and the provider/model metadata", () => {
    render(
      <StageOneResult
        status="complete"
        output={{
          name: "LaundryPal",
          oneLiner: "On-demand laundry pickup for busy professionals.",
          problem: "Doing laundry eats a weekend afternoon.",
          audience: "Urban professionals with disposable income.",
          valueProposition: "Get your weekend back.",
        }}
        provider="anthropic"
        model="claude-opus-4-8"
      />,
    );

    expect(screen.getByText("LaundryPal")).toBeInTheDocument();
    expect(screen.getByText("On-demand laundry pickup for busy professionals.")).toBeInTheDocument();
    expect(screen.getByText("Doing laundry eats a weekend afternoon.")).toBeInTheDocument();
    expect(screen.getByText("Urban professionals with disposable income.")).toBeInTheDocument();
    expect(screen.getByText("Get your weekend back.")).toBeInTheDocument();
    expect(screen.getByText("Generated by anthropic · claude-opus-4-8")).toBeInTheDocument();
  });

  it("renders the persisted error message for a failed record", () => {
    render(<StageOneResult status="failed" error="Anthropic request failed" />);

    expect(screen.getByText("Stage failed")).toBeInTheDocument();
    expect(screen.getByText("Anthropic request failed")).toBeInTheDocument();
  });
});
