import type { IdeaSummary } from "@launchblitz/workflow";

export type StageOneResultProps =
  | { status: "complete"; output: IdeaSummary; provider: string; model: string }
  | { status: "failed"; error: string };

export function StageOneResult(props: StageOneResultProps) {
  if (props.status === "failed") {
    return (
      <div className="rounded-[1.6rem] border border-red-500/20 bg-red-500/[0.05] p-5">
        <p className="text-[0.72rem] font-semibold uppercase tracking-[0.24em] text-red-300">
          Stage failed
        </p>
        <p className="mt-3 text-sm leading-6 text-[#ECEFF1]/76">{props.error}</p>
      </div>
    );
  }

  const { output, provider, model } = props;
  return (
    <div className="space-y-3 rounded-[1.6rem] border border-white/10 bg-white/[0.03] p-5">
      <div>
        <p className="text-[0.68rem] uppercase tracking-[0.24em] text-[#CFD8DC]/45">Name</p>
        <p className="mt-1 text-sm text-white">{output.name}</p>
      </div>
      <div>
        <p className="text-[0.68rem] uppercase tracking-[0.24em] text-[#CFD8DC]/45">One-liner</p>
        <p className="mt-1 text-sm text-[#ECEFF1]/85">{output.oneLiner}</p>
      </div>
      <div>
        <p className="text-[0.68rem] uppercase tracking-[0.24em] text-[#CFD8DC]/45">Problem</p>
        <p className="mt-1 text-sm text-[#ECEFF1]/85">{output.problem}</p>
      </div>
      <div>
        <p className="text-[0.68rem] uppercase tracking-[0.24em] text-[#CFD8DC]/45">Audience</p>
        <p className="mt-1 text-sm text-[#ECEFF1]/85">{output.audience}</p>
      </div>
      <div>
        <p className="text-[0.68rem] uppercase tracking-[0.24em] text-[#CFD8DC]/45">Value proposition</p>
        <p className="mt-1 text-sm text-[#ECEFF1]/85">{output.valueProposition}</p>
      </div>
      <p className="text-[0.68rem] text-[#CFD8DC]/45">
        Generated by {provider} · {model}
      </p>
    </div>
  );
}
